### ISSUE TITLE
why the soname in the hiredis1.0.2 is still 1.0.0

### ISSUE THREAD

**Issue by emmataobao** [redis/hiredis#1006]
Hi ,

i try to upgrade the hiredis from version 1.0.0 to version 1.0.2, find the generated  so file is still libhiredis.so.1.0.0.
/usr/bin/gcc -shared -Wl,-soname,libhiredis.so.1.0.0 -o libhiredis.so alloc.o net.o hiredis.o sds.o async.o read.o sockcompat.o

How could i check i upgrade successfully?

**Comment by michael-grunder** [comment]
It's because there is identical API and ABI compatibility between v1.0.2 and v1.0.0, so the SONAME should remain the same.

The idea is that packages that depend on hiredis don't need to be rebuilt, and there are many of those.  You can see #990 for a more detailed discussion of the matter.

I actually erroneously bumped the `SONAME` in `v1.0.1` which is why the quick release of `v1.0.2`.

In terms of how to tell which versions you have installed you can use `ldconfig -p|grep hiredis`.  If you want to make sure a binary is linking to the right version of hiredis you can use `ldd <your binary>`

**Comment by michael-grunder** [comment]
Closing this issue but feel free to ask more questions about this.
