### ISSUE TITLE
command_timeout option does not work in hiredis-cluster

### ISSUE THREAD

**Issue by wangfuqiang** [redis/hiredis#1060]
hiredis-cluster with hiredis version hiredis-1.0.0

I set command_timeout（10ms） with redisSetTimeout， some redis read request still cost more than 10ms？

any one has any advice？

**Comment by michael-grunder** [comment]
I'm not sure I totally understand the question.  Are you saying even with the timeout hiredis still blocks for more than 10ms at times?

**Comment by MichaelSuen-thePointer** [comment]
Maybe it is because some event libarary adapters does not support timeout.
You can check "adapters/<the library adapter you are using>.h" for assignment for `scheduleTimer`, if it is not assigned, then the adapter does not support timeout.

For example, `adapters/macosx.h`, `adapters/qt.h`, `adapters/ae.h`, `adapters/glib.h`, `adapters/ivykis.h` does not support timeout, which one are you using?

I added timeout support  for libuv adapter.

**Comment by michael-grunder** [comment]
Closing since I think the question has been answered
