### ISSUE TITLE
The features used are not compatible with the specified minimum version of cmake 3.0 for WIN32.

### ISSUE THREAD

**Issue by SRyabinin** [redis/hiredis#1105]
ADD_COMPILE_DEFINITIONS requires 3.12
TARGET_FILE_BASE_NAME requeres cmake 3.15

**Comment by michael-grunder** [comment]
Thanks for the report,

This is actually a tricky one as It looks like we only need that much newer version of CMake for windows builds.  

Moving the minimum version of CMake for both Linux and Windows from a version released in 2008 to one released in 2019 seems likely to cause a great deal of pain.

[According to this](https://unix.stackexchange.com/questions/535052/what-cmake-version-can-i-rely-on-in-current-popular-linux-distributions) it would break hiredis on several distros.

Since it doesn't appear possible to put `CMAKE_MINIMUM_REQUIRED` in a conditional, the only solution is to rework `CMakeLists.txt` to not use those new features.

We could also document this Windows specific problem in `CMakeLists.txt`.  

let me know if you have any other suggestions

cc @chayim

**Comment by SRyabinin** [comment]
Hi @michael-grunder  
My project uses cmake 3.10. So I have to rework CMakeLists.txt to not use the new features.
`ADD_COMPILE_DEFINITIONS(_CRT_SECURE_NO_WARNINGS WIN32_LEAN_AND_MEAN) `
replaced to
`set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /D_CRT_SECURE_NO_WARNINGS /D_WIN32_LEAN_AND_MEAN")`

`INSTALL(FILES $<TARGET_FILE_DIR:hiredis_static>/$<TARGET_FILE_BASE_NAME:hiredis_static>.pdb`
replaced to

```
    INSTALL(FILES $<TARGET_FILE_DIR:hiredis_static>/$<TARGET_NAME:hiredis_static>${CMAKE_DEBUG_POSTFIX}.pdb
        DESTINATION ${CMAKE_INSTALL_LIBDIR}
        CONFIGURATIONS Debug)

    INSTALL(FILES $<TARGET_FILE_DIR:hiredis_static>/$<TARGET_NAME:hiredis_static>${CMAKE_RELEASE_POSTFIX}.pdb
        DESTINATION ${CMAKE_INSTALL_LIBDIR}
        CONFIGURATIONS RelWithDebInfo Release)

```

**Comment by michael-grunder** [comment]
@SRyabinin Would you be willing to open a PR with those modifications?  

Also, I'm sadly not very familiar with CMake so let me know if your changes have other side effects (as opposed to using the newer CMake features).

**Comment by michael-grunder** [comment]
Hi, @SRyabinin I took a crack at these changes [in this commit on my fork](https://github.com/michael-grunder/hiredis/commit/7a5bda63611bfd5f6fed80b4b5f9994c4870423a).

I honestly know almost nothing about CMake so if you could take a look that would be great.

cc @kristjanvalur @bjosv You've both updated `CMakeLists.txt` so feel free to comment.

**Comment by michael-grunder** [comment]
I created a draft PR #1116
