### ISSUE TITLE
Would hiredis support compiling in windows?

### ISSUE THREAD

**Issue by xujg** [redis/hiredis#137]

**Comment by echoma** [comment]
I have forked hiredis and just make it works under Cygwin today:
https://github.com/echoma/hiredis-cygwin

This fork currently based on hiredis-0.13.0. All test cases are PASSED excluding UNIX-SOCKET cases, because I don't have a redis server in my Cygwin env. 
I am using select() to simulate the blocking socket I/O with timeout which Cygwin does not support. The default timeout out values is set to 600 seconds which is also the default timeout on most distributions. 

As a result of using select(), the fd of redis client can not be greater than 1023. So I think that currently my work is only helpful for those who wanna do daily development and basic test on Windows but deploy the production binaries on Linux.
