### ISSUE TITLE
Hiredis client close client connections after idle timeout 

### ISSUE THREAD

**Issue by suriu1981** [redis/hiredis#307]
Hello,
Is there a way to monitor for an idle redis connections using hiredis client C API's and close them?

Just like "timeout xxx" parameter in redis.conf which help server to silently close the idle client connections after timeout value.But server not notify the client about the closed connections.

-Thanks.

**Comment by carlosabalde** [comment]
I think there is not such function in the C API. What I'm doing in a project to workaround that limitation is directly using the `poll` function. It's not a great solution, but it may be helpful for your case too :)

```
#include <poll.h>

...

struct pollfd fds;
fds.fd = context->fd;
fds.events = POLLOUT;
if ((poll(&fds, 1, 0) != 1) || (fds.revents & POLLHUP)) {
    free_redis_context(context);
    context = NULL;
}
```

**Comment by suriu1981** [comment]
Thanks for your reply.
It's good to know how to poll on a client connection.But It does not serve my purpose.
I want some thing like set idle timeout on each connection created and a call back gets triggered when idle time elapses and then close that connection etc.
I am not quite sure but would like to know if it's possible at all directly/or indirectly using hiredis API's.

**Comment by mattsta** [comment]
> It's good to know how to poll on a client connection.But It does not serve my purpose.

The third parameter to `poll()` is a timeout for that fd.  So, it essentially does what you want by setting a timeout per-connection.

Generic idle timeouts on clients almost doesn't make sense because Redis allows blocking commands that can potentially remain open for an unlimited amount of time.  We probably wouldn't want to run a `BLPOP` then have a client expire because no other operations happened before the client-side timeout.
