### ISSUE TITLE
Memory corruption and segfault in redisAsyncHandleWrite

### ISSUE THREAD

**Issue by Taxopr** [redis/hiredis#310]
I'm facing strange cases of memory corruptions and segmentation faults while using hiredis async API (hiredis 0.10.1).
In all cases call stack looks like:
...................................................
#6  __redisAsyncFree (ac=ac@entry=0xcbfc10) at async.c:244
#7  0x00007f731d6890e6 in __redisAsyncDisconnect (ac=0xcbfc10) at async.c:298
#8  redisAsyncHandleWrite (ac=0xcbfc10) at async.c:485
...................................................

Looks like the internal structure of redisContext or redisAsyncContext is damaged, but I cannot find any dangerous code on my side.

In all cases in redisContext err==1 and errstr=='getsockopt(SO_ERROR): Socket operation on non-socket'.

Unfortunately, error reproduces only under heavy load in production, so I cannot reproduce it in debugger. All I have now is several core dumps.

Can you give me any idea, how to debug this issue?

**Comment by mattsta** [comment]
0.10.1 is almost 4 years old.  Can you upgrade to a recent release and try again?  (probably don't want to rely on OS-provided packages)

**Comment by Taxopr** [comment]
Upgrading hiredis is heavy feature, since other libraries require 0.10.1 and haven't been properly tested with new versions. Is there any known memory-related features in 0.10.1?

**Comment by mattsta** [comment]
Nothing I can think of off hand.  Since you're using async, make sure any custom adapter code is correct too. Check you aren't manually freeing connections when the async disconnect also frees the connection.  Double frees are easy ways to introduce crashes/memory corruption.  Also try running your code under valgrind — it'll be noisy if your usage is incorrect from a memory layout perspective.

Other than that, 0.10.1 *is* a 4 year old package, so upgrading is the next step to further debugging.
