### ISSUE TITLE
how does redisCommandArgv use?

### ISSUE THREAD

**Issue by ballbillow** [redis/hiredis#317]
int command_argc = 3;
char* command_argv[] = {"INFO", "SET BILLOWQIU ABC", "GET BILLOW"};
reply = (redisReply*)redisCommandArgv(c, command_argc, command_argv, NULL);
if(reply != NULL)
{
    std::cout << "reply type: " << reply->type << std::endl;
    std::cout << "reply len: " << reply->len << ", err: " << reply->str << std::endl;
    freeReplyObject(reply);
}
will out put:
"reply type: 6
reply len: 16, err: ERR syntax error"

char* command_argv[] = {"SET BILLOW abc", "SET BILLOWQIU ABC", "GET BILLOW"};
will out put:
"reply type: 6
reply len: 36, err: ERR unknown command 'SET BILLOW abc'"

**Comment by badboy** [comment]
You can't send multiple commands with a single `redisCommandArgv`.

This works:

```c
char* command_argv[] = {"SET", "BILLOW", "abc"};
redisCommandArgv(c, 3, command_argv, NULL);
```

The Redis protocol sends everything length-prefixed, that's why it needs to know what each argument and its length is.
If you need to send multiple commands, you have to do so manually.
In case you already got a simple string like `"SET BILLOW abc"`, use `redisCommand`, which takes the full command as a string. For more please read the [documentation in the README](https://github.com/redis/hiredis/blob/master/README.md)
