### ISSUE TITLE
inline keyword redefinition and <sys/time.h> include

### ISSUE THREAD

**Issue by progopis** [redis/hiredis#348]
I tried to build project on Windows and get macro redefinition error here:

hiredis\win32.h

```#ifndef inline```
```#define inline __inline```
``` #endif ```

I commented these lines.

Another issue fix:

hiredis\hiredis.h

```#ifndef _WIN32 // there is no header sys/time.h for Visual C++ 2013```
```#include <sys/time.h> /* for struct timeval */```
```#endif // _WIN32```

When these issues were fixed, I successfully build library.

**Comment by badboy** [comment]
I have absolutely no idea of Windows development. Currently hiredis has only limited support for Windows (exactly as much as is needed to build hiredis-node and hiredis-py for Windows).
I thus have to rely on appveyor for all Windows testing. 

Looking through #52, it seems to have the same changes in there, so I might even atleast take those in, though I did not receive any reports of failed hiredis-{node/py} installs because of this.
