### ISSUE TITLE
libhiredis.so.0.13 not found

### ISSUE THREAD

**Issue by zhouhoo** [redis/hiredis#526]
env:  redis  latest , hiredis latest.  ubuntu 16.04 .

compile ok ,install ok , but  when run my demo, it report:
`libhiredis.so.0.13 can not found ` error.

I make sure the file is located in /usr/local/lib and  ldconfig  -v  show it really there.

so why come out this?

**Comment by michael-grunder** [comment]
Your system probably just isn't seeing the hiredis .so file because it's not set up to look in `/usr/local/lib`.  You can add this to `$LD_LIBRARY_PATH` or add `/usr/local/lib/` to your `/etc/ld.so.conf` file and then run `sudo ldconfig`.

You'll want to make sure that hiredis is installed in `/usr/local/lib` but that's where it is on my system and I am running Ubuntu.

**Comment by zhouhoo** [comment]
thank you , but I have already done what you have mentioned. Finally , I found it was the link error:  I should built a 32 bit rather than 64 bit.
