### ISSUE TITLE
hiredis async client connection  closewait

### ISSUE THREAD

**Issue by lyfunny** [redis/hiredis#538]
reids server close idle conn , but redis client connection is in closewait status, disconnectCallback not called, pRedisContext redisAsyncCommandArgv return ok ,but  command callback func not called also, this like aeProcessEvents not work,if it work , soket read and write will find conn is in closewait,then hireds will return error and __redisAsyncDisconnect will called,and conn will be closed. this happen sometimes,mostly when server close conn,client disconnectCallback will called and whill reconnet,

**Comment by rollingxiaoxiao** [comment]
"when redisAsyncDisconnect is called,  it tries to do a clean disconnect from Redis, meaning it stops new commands from being issued but tries to flush the output buffer and execute callbacks for all remaining replies. When this function is called from a callback, there might be more replies and we can safely defer disconnecting to redisProcessCallbacks(). Otherwise, we can only disconnect immediately
when there are no pending callbacks. "

**Comment by michael-grunder** [comment]
Going to close this old issue since there hasn't been any activity in a year
