### ISSUE TITLE
clients timeout frequently

### ISSUE THREAD

**Issue by hustguoguo** [redis/hiredis#572]
I'm using redis as a online servive. the request latency is very import, i set it to 5ms. I find that, there are frequently timeouts. Because there are many clients and each client has many threads, the number of concurrent connections is about 10k to one instance. The qps of one redis instance is about 4k. why this happend? This problem confuses me several days. anyone can help me? Thank you!

**Comment by badboy** [comment]
Request timeouts can have a variety of reasons. I don’t know your application.
This however is unlikely directly an issue/bug of hiredis, the client library, so it’s not the right place to get help for your problem anyway.
You can try the mailing list, the IRC or the subreddit in order to get better help.
