### ISSUE TITLE
not friendly to judge redis cache expire or not

### ISSUE THREAD

**Issue by g10guang** [redis/hiredis#600]
```c
redisReply *reply = (redisReply *)redisCommand(this->rc, "hmget person:%d name email", person.id());
```

No matter person:id key exist or not, `reply->type == REDIS_REPLY_ARRAY`.

I don't know how to judge the hash is expired or not. PS: I don't want to execute `expire key` before every redis command.

I want it behaves as:

```
redisReply *reply = (redisReply *)redisCommand(this->rc, "hget person:%d email", person.id());
```

If person:id does not exist,  `reply->type == REDIS_REPLY_NIL`.

If hiredis gets some ways to do it, please inform me. Thank you. 😊

PS: Below is my test case:

```
127.0.0.1:6379> hmget person:2 name email
1) (nil)
2) (nil)

127.0.0.1:6379> hget person:2 name
(nil)
```

Maybe this behavior is just like how redis do.

**Comment by michael-grunder** [comment]
Hi,

Hiredis is simply returning whatever value Redis replies with.  In this case, the reply will be the same for a key that never existed, and one that did exist but has now expired.

I'm not sure what your app is trying to do specifically, but if you need to distinguish between the two conditions you can always use additional keys for that.

Again it depends on what you're trying to do but you could use a set or sets to mark an ID as having existed, and then check the set and your hash.  If a small error rate is acceptable you could use a HyperLogLog for the existence check.

I'm going to close the issue because this isn't a bug in Hiredis.  You may want to ask about solutions over at the [Redis subreddit](http://www.reddit.com/r/redis) or the mailing list.  :smile:
