### ISSUE TITLE
Maybe incorrect `redisContextSetTimeout` implement for windows.

### ISSUE THREAD

**Issue by heroboy** [redis/hiredis#695]
```c++
int redisContextSetTimeout(redisContext *c, const struct timeval tv) {
    if (setsockopt(c->fd,SOL_SOCKET,SO_RCVTIMEO,&tv,sizeof(tv)) == -1) {
        __redisSetErrorFromErrno(c,REDIS_ERR_IO,"setsockopt(SO_RCVTIMEO)");
        return REDIS_ERR;
    }
    if (setsockopt(c->fd,SOL_SOCKET,SO_SNDTIMEO,&tv,sizeof(tv)) == -1) {
        __redisSetErrorFromErrno(c,REDIS_ERR_IO,"setsockopt(SO_SNDTIMEO)");
        return REDIS_ERR;
    }
    return REDIS_OK;
}
```
https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-setsockopt

On windows,the argument of  `SO_RCVTIMEO` shoud be a DWORD in milliseconds. And `timeval` is a two long variable struct. The first long is `sec`. So when you want set 1 second timeout,then it will be 1ms.

**Comment by michael-grunder** [comment]
Hi @heroboy,

This is indeed a bug.  There are two open PRs that address it currently:

https://github.com/redis/hiredis/pull/662
https://github.com/redis/hiredis/pull/670/files

I can't be of much more help since I don't have a Windows machine and am not sure if there are plans to merge them any time soon.
