### ISSUE TITLE
Fix makefile on arch linux

### ISSUE THREAD

**Issue by caseus-cattus** [redis/hiredis#719]
make install copy and link libhiredis.so in /usr/local/lib, but on start program, it crash with:
` error while loading shared libraries: libhiredis.so.0.14: cannot open shared object file: No such file or directory`

It should solve problem:
`sudo cp /usr/local/lib/libhiredis.so /usr/lib/`

Arch linux 5.3.1

**Comment by michael-grunder** [comment]
Hi @caseus-cattus,

I'll look into what the best practices might be for this, but you can use the Makefile as is by specifying your own prefix:

```bash
$ PREFIX=/usr/ make install
```

**Comment by michael-grunder** [comment]
I think the right way to handle this is to create a config file in `/etc/ld.so.conf.d` that has `/usr/local/lib` in it.

Then either run `ldconfig` or restart the system and the system will be able to  find hiredis in `/usr/local/lib`.

I'll close the issue because we don't want hiredis installing in `/usr/local` since that's for platform packages.
