### ISSUE TITLE
sds.h warning C4244

### ISSUE THREAD

**Issue by irov** [redis/hiredis#735]
My code compile with flag **warning treated as error** and i get warning
```
hiredis\sds.h(101): warning C4244: 'return': conversion from 'uint64_t' to 'size_t', possible loss of data
hiredis\sds.h(126): warning C4244: 'return': conversion from 'uint64_t' to 'size_t', possible loss of data
hiredis\sds.h(194): warning C4244: 'return': conversion from 'uint64_t' to 'size_t', possible loss of data
```

**Comment by michael-grunder** [comment]
Is `size_t` 32 bits wide on your system?

What's the exact OS you're compiling on.  I assume some variant of Windows because of the backslashes but more specific information would be useful.

This conversion is likely safe because if your `size_t` is only 32 bits wide, we can't have malloced more memory than that anyway (since malloc will take a `size_t`).

**Comment by irov** [comment]
> Is `size_t` 32 bits wide on your system?
Windows, MSVC 16 (2019) x86

> What's the exact OS you're compiling on. I assume some variant of Windows because of the backslashes but more specific information would be useful.
You're right!
 
> This conversion is likely safe because if your `size_t` is only 32 bits wide, we can't have malloced more memory than that anyway (since malloc will take a `size_t`).
Yes, it's correct, but generate warning. And if i compile code with /WX (warning as error) i get error :(

**Comment by michael-grunder** [comment]
There aren't any current plans to fix this warning in Windows so I'll close the issue.
