### ISSUE TITLE
sds.c sdscatvprintf, the static buf is too small

### ISSUE THREAD

**Issue by originals-tz** [redis/hiredis#743]
maybe you can use a macro to set the size of it

**Comment by michael-grunder** [comment]
I'm not against using a `#define` for this but how is it too small for your use case?

I assume you're seeing too many reallocations which is affecting performance?

**Comment by originals-tz** [comment]
yes, now, i have 2 kinds of data

```
sizeof(data_1) < 1024

sizeof(data_2) > 1024
```

when i upload the data_2, it will call the `s_malloc`, it affect the performance, so, i do this
```c
//sds.c sdscatvprintf

#define BIG_STATIC_BUF_SIZE 1024 * 1024

char staticbuf[1024]; // as default buffer
static __thread char big_staticbuf[BIG_STATIC_BUF_SIZE]; //i think use macro to define the size is better

char *buf = staticbuf;
if (buflen > sizeof(big_staicbuf)
    //use s_malloc
else if (buflen > sizeof(staticbuf
    buf = big_staticbuf;
```

**Comment by michael-grunder** [comment]
If you need extreme performance (and have verified that command construction is the bottleneck), have you considered constructing the `RESP` command manually?

There's no harm in moving from a hard-coded size to a `#define`d one, but I wouldn't want to modify this in a way that people could easily break their code (because we'll deal with those related issue reports :smile:)

**Comment by originals-tz** [comment]
Ok, thanks for your reply
