### ISSUE TITLE
error while loading shared libraries: libhiredis.so.0.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by guotie** [redis/hiredis#80]
when i update hiredis from version 0.10.0 to version 0.10.1, recompile my code, run it, it dump following errors:
 error while loading shared libraries: libhiredis.so.0.10: cannot open shared object file: No such file or directory

but the file  libhiredis.so.0.10 IS in /usr/lib

I am sure this problem not appear in version 0.10.0.

**Comment by AntonioCS** [comment]
I solved this by running
`sudo ldconfig`
Which I believe updated some sort of lib cache and that fixed the issue.

**Comment by shabhu18** [comment]
I facing the same problem
i tried 

> sudo ldconfig
the command executed properly but error still exits .
rtabmap: error while loading shared libraries: librtabmap_core.so.0.11: cannot open shared object file: No such file or directory


can someone help

**Comment by badboy** [comment]
@shabhu18 That is an entirely different problem. Seems like your `librtabmap_core.so` is missing or broken.

**Comment by jacksonkr** [comment]
@shabhu18 

I ran into this same issue and I've found that it's because `LD_LIBRARY_PATH` is undefined so here's what worked for me:

I found `librtabmap_core.so.0.11` in my `rtabmap` build folder so I added that path using

`export LD_LIBRARY_PATH=$HOME/Downloads/rtabmap/bin`

or to `/usr/local/lib` or wherever you find `librtabmap_core.so.0.11` on your machine. If you don't know where it is you can try

`sudo find . -name "librtabmap_core.so.0.11"`

**Comment by onehandofLM** [comment]
确保你的/etc/ld.so.conf里面有 /usr/local/lib 这一行 没有的话vim编辑在尾行加上
然后 sudo ldconfig
