### ISSUE TITLE
libhiredis to use in reJson module

### ISSUE THREAD

**Issue by baskar-kumar** [redis/hiredis#803]
Iam calling redis json commands using hiredis library. In order to set the value for a reJSON, i have executed in code as below

redisCommand(ctx , "JSON.SET key  .path  \'\"adduser\"\'");

result in error 
ERR JSON lexer error SPECIAL_EXPECTED at position 11

From redis monitor i can see that command received from hiredis is as 
"JSON.SET" key" ".path" "'\"adduser\"'"

removing the \" here makes it successful, but  how to achieve the same from hiredis client

**Comment by michael-grunder** [comment]
I've never really used rediJson but the trick is just escaping your strings.

This works:
```c
    r = redisCommand(c, "JSON.SET %s . {%s:%s}", "foo", "\"path\"", "\"bar\"");
    r = redisCommand(c, "JSON.SET %s .path %s", "foo", "\"baz\"");
```

And this does as well:
```c
    r = redisCommand(c, "JSON.SET %s . {\"%s\":\"%s\"}", "foo", "path", "bar");
    r = redisCommand(c, "JSON.SET %s .path \"%s\"", "foo", "baz");
```

I'm going to close the issue because this isn't a bug in hiredis but I hope I answered the question.

You can also check out the [Redis gitter page](https://gitter.im/Redis/Lobby) for general questions.
