### ISSUE TITLE
 error: initializer element is not a compile-time constant

### ISSUE THREAD

**Issue by adrian-rt** [redis/hiredis#875]
I get this error :

error: initializer element is not a compile-time constant
redisContext *c = redisConnect("127.0.0.1", 6379);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
afl-fuzz.c:346:1: error: expected identifier or '('
if (c == NULL || c->err) {
^
2 errors generated.
make: *** [Makefile:73: afl-fuzz] Error 1
~/Downloads/DIE_v2

thanks.

**Comment by michael-grunder** [comment]
I don't really understand what I'm looking at.

I assume you're trying to fuzz test hiredis (or a project that uses hiredis)?  I would need more information in order to help you.

Are the lines you're having a problem with outside of a function?

```c
#include <stdio.h>
#include <hiredis/hiredis.h>

// These lines being outside of any function will cause the errors you're seeing
redisContext *c = redisConnect("localhost", 6379);
if (c == NULL || c->err) {
    printf("Oh no\n");
}

int main(void) {
}
```

Change it so that the lines are inside of your main

```c
#include <stdio.h>
#include <hiredis/hiredis.h>

int main(void) {
    redisContext *c = redisConnect("localhost", 6379);
    if (c == NULL || c->err) {
        printf("Oh no\n");
    }
}
```

**Comment by michael-grunder** [comment]
I'm going to close the issue since this doesn't describe a bug in Hiredis, but I'm happy to help with your compile error if you post a complete code sample.
